language: node_js
node_js: 14
branches:
  only: main
cache:
  npm: false
  directories:
    - .yarn/cache
deploy:
  email: npmjs@charlesstover.com
  provider: npm
  skip_cleanup: true
  api_key:
    secure:
  on:
    branch: main
install:
  - yarn
script:
  - yarn build
  - yarn test
